[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "icenet_sipn"
dynamic = ["version", "readme"]
requires-python = ">=3.8"
description = "Library to compute metrics from IceNet library for SIPN"
license = { file = "LICENSE" }
authors = [{name = "British Antarctic Survey"}]
maintainers = [
  { email = "bryald@bas.ac.uk" }
]
dependencies = [
  "icenet",
  "ipywidgets",
  "matplotlib",
  "netcdf4",
  "pip",
  "rioxarray",
  "setuptools",
  "xarray[io]"
]
classifiers = [
    "Development Status :: 3",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[tool.setuptools]
py-modules = ["icenet_sipn"]

[tool.setuptools.dynamic]
version = {attr = "icenet_sipn.__version__"}
readme = {file = ["README.md"]}

[project.optional-dependencies]
dev = [
  "watchdog",
  "coverage",
  "twine",
  "pytest",
  "build",
  "importlib_metadata"
]
docs = [
  "jinja2",
  "Sphinx"
]

[project.urls]
"Source" = "https://github.com/icenet-ai/icenet-sipn-arcus"
"Issue tracker" = "https://github.com/icenet-ai/icenet-sipn-arcus/issues"

[tool.pytest.ini_options]
addopts = "-ra --ignore=setup.py"
testpaths = [
    "icenet_sipn",
]
